version: '2.1'
services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password --expire_logs_days=3 --secure-file-priv="" --local-infile=1
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE, fix error mbind: Operation not permitted
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=$MW_DB_INSTALLDB_PASS
            - MYSQL_DATABASE=$MW_DB_NAME
        volumes:
            - ./__initdb:/docker-entrypoint-initdb.d
            - ./_data/mysql:/var/lib/mysql

    web:
        image: ghcr.io/wikiteq/mediawiki:1.35.3-20210901-312e686
        restart: unless-stopped
        links:
            - db
            - redis
            - elasticsearch
        environment:
            # DEFINE THIS VARIABLES IN .env FILE
            - MW_NCBI_TAXONOMY_API_KEY
            - MW_RECAPTCHA_SITE_KEY
            - MW_RECAPTCHA_SECRET_KEY
            - MW_ADMIN_USER
            - MW_ADMIN_PASS
            - MW_DB_NAME
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS
            - MW_DB_USER=root
            - MW_DB_PASS=$MW_DB_INSTALLDB_PASS
            - MW_SECRET_KEY

#            - XDEBUG_CONFIG=remote_host=0.0.0.0 remote_enable=1 remote_autostart=Off remote_connect_back=On
            - MW_SITE_SERVER=${MW_SITE_SERVER:-https://bugsigdb.org}
            - MW_SITE_NAME=BugSigDB
            - MW_SITE_LANG=en
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_AUTOUPDATE=true
            - MW_MAIN_CACHE_TYPE=CACHE_REDIS
            - MW_LOAD_SKINS=Vector,chameleon
            - MW_DEFAULT_SKIN=chameleon
            - MW_LOAD_EXTENSIONS=GTag,CodeEditor,Nuke,ParserFunctions,ReplaceText,WikiEditor,Interwiki,CodeEditor,Scribunto,SyntaxHighlight_GeSHi,DataTransfer,Variables,PubmedParser,CodeMirror,Loops,MyVariables,Arrays,DisplayTitle,NCBITaxonomyLookup,SemanticExtraSpecialProperties,SemanticResultFormats
            - MW_SEARCH_TYPE=CirrusSearch
            - MW_PROXY_SERVERS=varnish:80
        volumes:
            - ./_data/mediawiki:/mediawiki
            - ./_logs/httpd:/var/log/httpd
            - ./_settings/:/var/www/html/w/_settings
            - ./_resources/.htaccess:/var/www/html/.htaccess
            - ./_resources/favicon.ico:/var/www/html/w/favicon.ico
            - ./_resources/logo.png:/var/www/html/w/logo.png
            - ./_resources/chameleon:/var/www/html/w/skins/chameleon/custom
            - ./_resources/footer_icons/cuny.png:/var/www/html/w/cuny.png
            - ./_resources/footer_icons/mw.png:/var/www/html/w/mw.png
            - ./_resources/footer_icons/smw.png:/var/www/html/w/smw.png
            - ./_resources/footer_icons/ww.png:/var/www/html/w/ww.png
            - ./_resources/extensions/SemanticDependencyUpdater:/var/www/html/w/extensions/SemanticDependencyUpdater

    redis:
        image: "redis:alpine"
        restart: unless-stopped
        volumes:
            - ./_data/redis:/data
#            - ./_resources/redis.conf:/usr/local/etc/redis/redis.conf

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
        restart: unless-stopped
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./_data/elasticsearch:/usr/share/elasticsearch/data

    matomo:
        image: matomo
        restart: unless-stopped
        links:
            - db
        ports:
            - "8182:80"
        environment:
            - MATOMO_DATABASE_HOST=db
            - MATOMO_DATABASE_DBNAME=matomo
            - MATOMO_DATABASE_USERNAME=root
            - MATOMO_DATABASE_PASSWORD=$MW_DB_INSTALLDB_PASS
        volumes:
            - ./_data/matomo:/var/www/html

    varnish:
        image: varnish:stable
        ports:
            - "${PORT:-8081}:80"
        links:
            - web
        tmpfs:
            - /var/lib/varnish:exec
        environment:
            - VARNISH_SIZE=${VARNISH_SIZE:-2G}
        volumes:
            - ./_resources/varnish.vcl:/etc/varnish/default.vcl
